/**
 * @author Andy Smith
 * @license [MIT](http://www.opensource.org/licenses/mit-license.php)
 */
(function ($) {
	'use strict';
	$.sceditor.locale["hu"] = {
		"Bold": "Félkövér",
		"Italic": "Dőlt",
		"Underline": "Aláhúzott",
		"Strikethrough": "Áthúzott",
		"Subscript": "Alsó index",
		"Superscript": "Felső index",
		"Align left": "Balra",
		"Center": "Középre",
		"Align right": "Jobbra",
		"Justify": "Sorkizárt",
		"Font Name": "Betűtípus",
		"Font Size": "Betű méret",
		"Font Color": "Betű szín",
		"Remove Formatting": "Formázás eltávolítása",
		"Cut": "Kivágás",
		"Your browser does not allow the cut command. Please use the keyboard shortcut Ctrl/Cmd-X": "A böngésző nem engedi a kivágást. Helyette próbáld a Ctrl+X-et.",
		"Copy": "Másolás",
		"Your browser does not allow the copy command. Please use the keyboard shortcut Ctrl/Cmd-C": "A böngésző nem engedi a másolást. Helyette próbáld a Ctrl+C-t.",
		"Paste": "Beillesztés",
		"Your browser does not allow the paste command. Please use the keyboard shortcut Ctrl/Cmd-V": "A böngésző nem engedi a beillesztést. Helyette próbáld a Ctrl+V-t.",
		"Paste your text inside the following box:": "Írd be a szöveget az alábbi dobozba:",
		"Paste Text": "Szöveg beillesztés",
		"Bullet list": "Lista",
		"Numbered list": "Számozott lista",
		"Undo": "Visszavonás",
		"Redo": "Újra",
		"Rows:": "Sorok:",
		"Cols:": "Oszlopok:",
		"Insert a table": "Tábla beszúrása",
		"Insert a horizontal rule": "Választóvonal beszúrása",
		"Code": "Kód beszúrása",
		"Width (optional):": "Szélesség:",
		"Height (optional):": "Magasság:",
		"Insert an image": "Kép beszúrása",
		"E-mail:": "E-mail:",
		"Insert an email": "E-mail beszúrása",
		"URL:": "URL:",
		"Insert a link": "Hivatkozás beszúrása",
		"Unlink": "Hivatkozás törlése",
		"More": "Mégtöbb...",
		"Insert an emoticon": "Emoticon beszúrása",
		"Video URL:": "Videó URL:",
		"Insert": "Beszúrás",
		"Insert a YouTube video": "YouTube videó beszúrása",
		"Insert current date": "Dátum beszúrása",
		"Insert current time": "Idő beszúrása",
		"Print": "Nyomtatás",
		"View source": "Forrás",
		"Description (optional):": "Szöveg:",
		"Enter the image URL:": "Add meg a kép URL-t:",
		"Enter the e-mail address:": "Add meg az e-mail címet:",
		"Enter the displayed text:": "Add meg a megjelenítendő szöveget:",
		"Enter URL:": "Add meg az URL-t:",
		"Enter the YouTube video URL or ID:": "Add meg a YouTube videó URL-t vagy ID-t:",
		"Insert a Quote":"Idézet beszúrása",
		"Invalid YouTube video": "Érvénytelen YouTube videó",
		"Left-to-Right": "Balról jobbra",
		"Right-to-Left": "Jobbról balra",
		"Maximize": "Teljes képernyő...",
		
		dateFormat: "day-month-year"
	}
})(jQuery);